const translations={
 English:{topLine:'Healthcare information made easier',accessibility:'Accessibility',findCare:'Find care',howItWorks:'How it works',assistant:'Health assistant',searchResults:'Search results',hospitalsFor:'Hospitals for',filters:'Filters',needHelp:'What do you need help with?',where:'Where?',search:'Search',filterResults:'Filter results',hospitalType:'Hospital type',services:'Services',distance:'Distance',clear:'Clear',matches:'matches',compareHospitals:'Compare hospitals',compareTitle:'See the details side by side.',compareIntro:'Compare the same information across hospitals so the important differences are easy to understand.'},
 Hindi:{topLine:'स्वास्थ्य जानकारी को समझना आसान बनाएं',accessibility:'सुलभता',findCare:'इलाज खोजें',howItWorks:'यह कैसे काम करता है',assistant:'हेल्थ असिस्टेंट',searchResults:'खोज परिणाम',hospitalsFor:'अस्पताल',filters:'फ़िल्टर',needHelp:'आपको किस मदद की जरूरत है?',where:'कहाँ?',search:'खोजें',filterResults:'परिणाम फ़िल्टर करें',hospitalType:'अस्पताल का प्रकार',services:'सेवाएँ',distance:'दूरी',clear:'साफ़ करें',matches:'परिणाम',compareHospitals:'अस्पतालों की तुलना',compareTitle:'जानकारी को एक साथ देखें।',compareIntro:'अस्पतालों की समान जानकारी साथ देखकर महत्वपूर्ण अंतर आसानी से समझें।'},
 Punjabi:{topLine:'ਸਿਹਤ ਜਾਣਕਾਰੀ ਨੂੰ ਸਮਝਣਾ ਆਸਾਨ ਬਣਾਓ',accessibility:'ਪਹੁੰਚਯੋਗਤਾ',findCare:'ਇਲਾਜ ਲੱਭੋ',howItWorks:'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',assistant:'ਹੈਲਥ ਅਸਿਸਟੈਂਟ',searchResults:'ਖੋਜ ਨਤੀਜੇ',hospitalsFor:'ਹਸਪਤਾਲ',filters:'ਫਿਲਟਰ',needHelp:'ਤੁਹਾਨੂੰ ਕਿਸ ਮਦਦ ਦੀ ਲੋੜ ਹੈ?',where:'ਕਿੱਥੇ?',search:'ਖੋਜੋ',filterResults:'ਨਤੀਜੇ ਫਿਲਟਰ ਕਰੋ',hospitalType:'ਹਸਪਤਾਲ ਦੀ ਕਿਸਮ',services:'ਸੇਵਾਵਾਂ',distance:'ਦੂਰੀ',clear:'ਸਾਫ਼ ਕਰੋ',matches:'ਨਤੀਜੇ',compareHospitals:'ਹਸਪਤਾਲਾਂ ਦੀ ਤੁਲਨਾ',compareTitle:'ਵੇਰਵੇ ਇਕੱਠੇ ਦੇਖੋ।',compareIntro:'ਹਸਪਤਾਲਾਂ ਦੀ ਇੱਕੋ ਜਿਹੀ ਜਾਣਕਾਰੀ ਨਾਲ ਮਹੱਤਵਪੂਰਨ ਫਰਕ ਆਸਾਨੀ ਨਾਲ ਸਮਝੋ।'},
 Bengali:{topLine:'স্বাস্থ্য তথ্য বোঝা আরও সহজ',accessibility:'অ্যাক্সেসিবিলিটি',findCare:'চিকিৎসা খুঁজুন',howItWorks:'কীভাবে কাজ করে',assistant:'হেলথ অ্যাসিস্ট্যান্ট',searchResults:'অনুসন্ধানের ফলাফল',hospitalsFor:'হাসপাতাল',filters:'ফিল্টার',needHelp:'আপনার কী ধরনের সাহায্য দরকার?',where:'কোথায়?',search:'খুঁজুন',filterResults:'ফলাফল ফিল্টার করুন',hospitalType:'হাসপাতালের ধরন',services:'সেবা',distance:'দূরত্ব',clear:'পরিষ্কার',matches:'ফলাফল',compareHospitals:'হাসপাতাল তুলনা',compareTitle:'তথ্য পাশাপাশি দেখুন।',compareIntro:'একই তথ্য পাশাপাশি দেখে গুরুত্বপূর্ণ পার্থক্য সহজে বুঝুন।'},
 Tamil:{topLine:'சுகாதார தகவலை எளிதாக புரிந்துகொள்ளுங்கள்',accessibility:'அணுகல்தன்மை',findCare:'சிகிச்சையைத் தேடுங்கள்',howItWorks:'எப்படி செயல்படுகிறது',assistant:'ஹெல்த் உதவியாளர்',searchResults:'தேடல் முடிவுகள்',hospitalsFor:'மருத்துவமனைகள்',filters:'வடிகட்டிகள்',needHelp:'எந்த உதவி தேவை?',where:'எங்கே?',search:'தேடு',filterResults:'முடிவுகளை வடிகட்டு',hospitalType:'மருத்துவமனை வகை',services:'சேவைகள்',distance:'தூரம்',clear:'அழி',matches:'முடிவுகள்',compareHospitals:'மருத்துவமனைகளை ஒப்பிடுங்கள்',compareTitle:'விவரங்களை அருகருகே பாருங்கள்.',compareIntro:'மருத்துவமனைகளின் ஒரே தகவலை அருகருகே பார்த்து முக்கிய வேறுபாடுகளை எளிதாக புரிந்துகொள்ளுங்கள்.'}
};
const langNames=['English','हिंदी','ਪੰਜਾਬੀ','বাংলা','தமிழ்'];
function currentLang(){return localStorage.getItem('curoLang')||'English'}
function setLanguage(lang){localStorage.setItem('curoLang',lang);applyLanguage();document.querySelectorAll('.language-btn').forEach(b=>b.innerHTML=`<span>◎</span> ${lang} <span class="chevron">⌄</span>`);document.querySelectorAll('.language-menu').forEach(m=>m.classList.remove('open'))}
function applyLanguage(){const lang=currentLang();const t=translations[lang]||translations.English;document.documentElement.lang=lang==='English'?'en':'hi';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t[key])el.textContent=t[key]})}
function initShell(){
 const menu=document.getElementById('mobileMenu'),menuBtn=document.getElementById('menuBtn'),langBtn=document.getElementById('languageBtn'),langMenu=document.getElementById('languageMenu');
 menuBtn?.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});
 langBtn?.addEventListener('click',e=>{e.stopPropagation();langMenu.classList.toggle('open');langBtn.setAttribute('aria-expanded',langMenu.classList.contains('open'))});
 langMenu?.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
 document.addEventListener('click',e=>{if(langMenu&&!langMenu.contains(e.target)&&!langBtn?.contains(e.target))langMenu.classList.remove('open')});
 document.getElementById('accessibilityBtn')?.addEventListener('click',()=>{const large=document.body.classList.toggle('large-text');document.body.classList.remove('high-contrast');showToast(large?'Larger text enabled':'Larger text disabled')});
 applyLanguage();
}
function showToast(message){const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.add('show');clearTimeout(window.curoToast);window.curoToast=setTimeout(()=>t.classList.remove('show'),2600)}
function compareList(){return JSON.parse(localStorage.getItem('curoCompare')||'[]')}
function setCompare(list){localStorage.setItem('curoCompare',JSON.stringify([...new Set(list)].slice(0,3)))}
function toggleCompare(id){let list=compareList();if(list.includes(id))list=list.filter(x=>x!==id);else if(list.length<3)list.push(id);else {showToast('You can compare up to 3 hospitals.');return list}setCompare(list);return list}
initShell();
