const CURO_HOSPITALS = [
 {id:'citycare',name:'CityCare Multispeciality Hospital',short:'CityCare Hospital',city:'Pune',area:'Kothrud',distance:2.4,type:'Multi-specialty',verified:true,rating:4.6,reviews:128,emergency:true,icu:true,diagnostics:true,cashless:true,cost:'₹25,000 — ₹1.2L',costValue:25000,departments:['Cardiology','Neurology','Orthopaedics','General Medicine'],address:'Kothrud, Pune, Maharashtra',phone:'+91 20 4000 2200',hours:'24 hours · Emergency open',about:'A multi-specialty hospital offering emergency services, diagnostics and specialist departments in one location.',beds:'250+',insurance:'Major insurance & cashless plans'},
 {id:'lifeline',name:'Lifeline Heart & Medical Centre',short:'Lifeline Medical Centre',city:'Pune',area:'Shivajinagar',distance:4.1,type:'Specialty',verified:true,rating:4.8,reviews:94,emergency:true,icu:true,diagnostics:true,cashless:true,cost:'₹30,000 — ₹1.5L',costValue:30000,departments:['Cardiology','Cardiac Surgery','Diagnostics'],address:'Shivajinagar, Pune, Maharashtra',phone:'+91 20 4100 1818',hours:'24 hours · Emergency open',about:'A focused cardiac-care centre with cardiology, diagnostics and critical-care services.',beds:'120+',insurance:'Selected insurance & cashless plans'},
 {id:'sanjeevani',name:'Sanjeevani General Hospital',short:'Sanjeevani Hospital',city:'Pune',area:'Wakad',distance:6.7,type:'Multi-specialty',verified:true,rating:4.4,reviews:71,emergency:true,icu:true,diagnostics:true,cashless:false,cost:'₹18,000 — ₹95,000',costValue:18000,departments:['Cardiology','General Medicine','Orthopaedics'],address:'Wakad, Pune, Maharashtra',phone:'+91 20 4300 7654',hours:'24 hours · Emergency open',about:'General and specialist care with emergency, ICU and diagnostic services.',beds:'180+',insurance:'Insurance accepted; cashless varies'},
 {id:'greenvalley',name:'Green Valley Medical Institute',short:'Green Valley',city:'Pune',area:'Baner',distance:8.3,type:'Multi-specialty',verified:false,rating:4.2,reviews:56,emergency:true,icu:false,diagnostics:true,cashless:true,cost:'₹22,000 — ₹1.05L',costValue:22000,departments:['Cardiology','Women’s Health','General Medicine'],address:'Baner, Pune, Maharashtra',phone:'+91 20 4550 1010',hours:'8 am — 10 pm · Emergency available',about:'A modern community hospital with specialist clinics and diagnostic services.',beds:'100+',insurance:'Major insurance & cashless plans'},
 {id:'metro',name:'MetroCare Institute of Health',short:'MetroCare',city:'Pune',area:'Hadapsar',distance:9.8,type:'Multi-specialty',verified:true,rating:4.5,reviews:83,emergency:true,icu:true,diagnostics:true,cashless:true,cost:'₹28,000 — ₹1.3L',costValue:28000,departments:['Cardiology','Oncology','Orthopaedics','Neurology'],address:'Hadapsar, Pune, Maharashtra',phone:'+91 20 4700 9000',hours:'24 hours · Emergency open',about:'A broad specialist hospital with critical care, diagnostics and multiple clinical departments.',beds:'300+',insurance:'Major insurance & cashless plans'},
 {id:'aarogyam',name:'Aarogyam Care Hospital',short:'Aarogyam Care',city:'Pune',area:'Viman Nagar',distance:11.2,type:'Multi-specialty',verified:false,rating:4.1,reviews:48,emergency:false,icu:true,diagnostics:true,cashless:false,cost:'₹16,000 — ₹88,000',costValue:16000,departments:['Cardiology','General Medicine','Diabetes'],address:'Viman Nagar, Pune, Maharashtra',phone:'+91 20 4820 3120',hours:'7 am — 11 pm',about:'A community-focused hospital with general and specialist outpatient services.',beds:'90+',insurance:'Insurance accepted; confirm cashless eligibility'}
];
function getHospital(id){return CURO_HOSPITALS.find(h=>h.id===id)||CURO_HOSPITALS[0]}
