const id=new URLSearchParams(location.search).get('id')||'1';
const root=document.getElementById('hospitalDetail');
async function loadHospital(){
  try {
    const h=(await apiHospital(id)).data;
    renderHospital(h);
  } catch(error) {
    const fallback=typeof getHospital==='function'?getHospital(id):null;
    if(fallback){renderHospital(fallback);showToast('Backend not connected — showing demo data.');}
    else root.innerHTML=`<section class="section"><div class="container empty-state"><h2>Hospital not found.</h2><p>${error.message}</p><a class="primary-btn" href="hospitals.html">Find care <span>→</span></a></div></section>`;
  }
}
function renderHospital(h){
 root.innerHTML=`<section class="detail-hero"><div class="container"><div class="breadcrumb"><a href="hospitals.html">Find care</a><span>›</span><span>${h.name}</span></div><div class="detail-head"><div class="detail-icon">✚</div><div class="detail-title"><div class="title-row"><h1>${h.name}</h1>${h.verified?'<span class="verified-pill">✓ Verified information</span>':''}</div><p>${h.type} · ${h.area}, ${h.city}</p><div class="rating-line"><span class="rating">★ ${h.rating}</span><span>${h.reviews} reviews</span><span>•</span><span>${h.hours}</span></div></div><button class="compare-btn" id="detailCompare">＋ Compare</button></div></div></section>
 <section class="section detail-section"><div class="container detail-layout"><div class="detail-main"><nav class="detail-tabs"><a href="#overview" class="active">Overview</a><a href="#services">Services</a><a href="#cost">Costs</a><a href="#location">Location</a></nav><section id="overview" class="detail-block"><span class="eyebrow">About this hospital</span><h2>Care information in one place.</h2><p>${h.about}</p><div class="info-grid"><div><small>Departments</small><strong>${h.departments.join(' · ')}</strong></div><div><small>Hospital size</small><strong>${h.beds} beds</strong></div><div><small>Insurance</small><strong>${h.insurance}</strong></div></div></section><section id="services" class="detail-block"><span class="eyebrow">Services & facilities</span><h2>What you can find here</h2><div class="service-grid">${(h.services||[]).map(s=>`<div class="service-item"><span>✓</span><strong>${s.name||s}</strong><small>${s.description||'Listed in the Curo hospital record.'}</small></div>`).join('')}</div></section><section id="cost" class="detail-block"><span class="eyebrow">Cost information</span><h2>Understand the estimate.</h2><div class="cost-highlight"><strong>${h.cost}</strong><p>Illustrative treatment range in this academic prototype. Actual charges depend on treatment, doctor, room, tests and other hospital services.</p></div></section><section id="location" class="detail-block"><span class="eyebrow">Location & contact</span><h2>Plan your visit.</h2><div class="location-box"><div class="map-placeholder"><span>⌖</span><strong>${h.area}</strong><small>${h.city}</small></div><div class="contact-info"><p><strong>Address</strong><br>${h.address}</p><p><strong>Phone</strong><br>${h.phone}</p><p><strong>Hours</strong><br>${h.hours}</p></div></div></section></div><aside class="detail-side"><div class="sticky-card"><span class="eyebrow">At a glance</span><div class="glance-row"><span>Estimated cost</span><strong>${h.cost}</strong></div><div class="glance-row"><span>Distance</span><strong>${h.distance} km</strong></div><div class="glance-row"><span>Emergency</span><strong>${h.emergency?'Available':'Not listed'}</strong></div><a class="primary-btn full-btn" href="tel:${h.phone.replace(/[^0-9+]/g,'')}">Call hospital <span>→</span></a><button class="secondary-btn full-btn" id="appointmentBtn" type="button">Request an appointment <span>→</span></button><button class="compare-btn full-btn" id="sideCompare">＋ Add to compare</button><button class="compare-btn full-btn" id="saveHospital">♡ Save hospital</button><small class="side-note">Curo is an information and comparison prototype. Always confirm availability, price and insurance eligibility with the hospital.</small></div></aside></div></section>`;
 const updateCompare=()=>{const active=compareList().includes(String(h.id));document.querySelectorAll('#detailCompare,#sideCompare').forEach(b=>{b.textContent=active?'✓ Added to compare':'＋ Add to compare';b.classList.toggle('active',active)})};
 document.querySelectorAll('#detailCompare,#sideCompare').forEach(b=>b.addEventListener('click',()=>{const l=toggleCompare(String(h.id));updateCompare();showToast(l.includes(String(h.id))?'Hospital added to comparison':'Hospital removed from comparison')}));updateCompare();
 const modal=document.createElement('div');modal.className='modal-lite';modal.id='appointmentModal';modal.innerHTML=`<div class="modal-lite-card" role="dialog" aria-modal="true" aria-labelledby="appointmentTitle"><div class="modal-head"><div><span class="eyebrow">Appointment request</span><h2 id="appointmentTitle">Request a visit at ${h.short_name||h.short}</h2><p class="muted">Your request is saved to the Curo database. The hospital is not automatically contacted.</p></div><button class="close-lite" type="button" id="closeAppointment">×</button></div><form id="appointmentForm"><div class="form-grid"><div class="form-field"><label>Your name</label><input name="name" required placeholder="Full name"></div><div class="form-field"><label>Phone</label><input name="phone" required placeholder="Mobile number"></div><div class="form-field"><label>Preferred date</label><input name="date" required type="date"></div><div class="form-field"><label>Preferred time</label><select name="time"><option>Morning</option><option>Afternoon</option><option>Evening</option></select></div><div class="form-field full"><label>Department</label><select name="department">${h.departments.map(d=>`<option>${d}</option>`).join('')}</select></div></div><br><button class="primary-btn" type="submit">Submit request <span>→</span></button></form></div>`;document.body.appendChild(modal);
 document.getElementById('appointmentBtn')?.addEventListener('click',()=>modal.classList.add('open'));document.getElementById('closeAppointment')?.addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
 document.getElementById('appointmentForm')?.addEventListener('submit',async e=>{e.preventDefault();const form=new FormData(e.target);try{await apiAppointment({hospital_id:h.id,name:form.get('name'),phone:form.get('phone'),date:form.get('date'),time:form.get('time'),department:form.get('department')});modal.classList.remove('open');e.target.reset();showToast('Appointment request saved.');}catch(err){showToast(err.message)}});
 const saveBtn=document.getElementById('saveHospital');const updateSaved=()=>{const saved=JSON.parse(localStorage.getItem('curoSaved')||'[]');const yes=saved.includes(String(h.id));if(saveBtn){saveBtn.textContent=yes?'♥ Saved':'♡ Save hospital';saveBtn.classList.toggle('active',yes)}};saveBtn?.addEventListener('click',()=>{let saved=JSON.parse(localStorage.getItem('curoSaved')||'[]');saved=saved.includes(String(h.id))?saved.filter(x=>x!==String(h.id)):[...saved,String(h.id)];localStorage.setItem('curoSaved',JSON.stringify(saved));updateSaved();showToast(saved.includes(String(h.id))?'Hospital saved':'Hospital removed from saved')});updateSaved();
}
loadHospital();
