(() => {
 const T={
  English:{topLine:'Healthcare information made easier',accessibility:'Accessibility',findCare:'Find care',howItWorks:'How it works',assistant:'Health assistant',eyebrow:'Care that starts with clarity',heroTitle:'Find the right care,',heroEm:'without the guesswork.',heroText:'Search hospitals by condition, location, treatment, facilities and estimated cost — all in one simple place.',needHelp:'What do you need help with?',where:'Where?',startKnow:'Start with what you know',lookingFor:'What are you looking for?',commonNeed:"You don't need to know the medical term. Choose a common care need to get started.",meetGuide:'Meet your care guide',notSure:'Not sure where to start?',askCuro:'Ask Curo.',morePeople:'Healthcare for more people',languageTitle:"Use Curo in the language you're comfortable with.",languageText:'Switch languages without losing the information you need.',ready:'Ready when you are',ctaTitle:'Find care with a little more clarity.',startSearching:'Start searching',academic:'Academic prototype'},
  Hindi:{topLine:'स्वास्थ्य जानकारी को समझना आसान बनाएं',accessibility:'सुलभता',findCare:'इलाज खोजें',howItWorks:'यह कैसे काम करता है',assistant:'हेल्थ असिस्टेंट',eyebrow:'स्पष्ट जानकारी से देखभाल की शुरुआत',heroTitle:'सही इलाज खोजें,',heroEm:'बिना अनुमान के।',heroText:'स्थिति, स्थान, इलाज, सुविधाओं और अनुमानित खर्च के आधार पर अस्पताल खोजें — एक ही जगह।',needHelp:'आपको किस मदद की जरूरत है?',where:'कहाँ?',startKnow:'जहाँ से आप शुरू कर सकते हैं',lookingFor:'आप क्या खोज रहे हैं?',commonNeed:'आपको मेडिकल शब्द जानने की जरूरत नहीं है। शुरुआत के लिए एक सामान्य जरूरत चुनें।',meetGuide:'आपका केयर गाइड',notSure:'कहाँ से शुरू करें समझ नहीं आ रहा?',askCuro:'क्यूरो से पूछें।',morePeople:'ज्यादा लोगों के लिए स्वास्थ्य सेवा',languageTitle:'क्यूरो अपनी पसंदीदा भाषा में इस्तेमाल करें।',languageText:'जरूरी जानकारी खोए बिना भाषा बदलें।',ready:'जब आप तैयार हों',ctaTitle:'थोड़ी अधिक स्पष्टता के साथ इलाज खोजें।',startSearching:'खोजना शुरू करें',academic:'शैक्षणिक प्रोटोटाइप'},
  Punjabi:{topLine:'ਸਿਹਤ ਜਾਣਕਾਰੀ ਨੂੰ ਸਮਝਣਾ ਆਸਾਨ ਬਣਾਓ',accessibility:'ਪਹੁੰਚਯੋਗਤਾ',findCare:'ਇਲਾਜ ਲੱਭੋ',howItWorks:'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',assistant:'ਹੈਲਥ ਅਸਿਸਟੈਂਟ',eyebrow:'ਸਪਸ਼ਟ ਜਾਣਕਾਰੀ ਨਾਲ ਦੇਖਭਾਲ ਦੀ ਸ਼ੁਰੂਆਤ',heroTitle:'ਸਹੀ ਇਲਾਜ ਲੱਭੋ,',heroEm:'ਬਿਨਾਂ ਅੰਦਾਜ਼ੇ ਦੇ।',heroText:'ਬਿਮਾਰੀ, ਸਥਾਨ, ਇਲਾਜ, ਸਹੂਲਤਾਂ ਅਤੇ ਅੰਦਾਜ਼ੇ ਖਰਚ ਦੇ ਆਧਾਰ ਤੇ ਹਸਪਤਾਲ ਲੱਭੋ — ਇੱਕੋ ਥਾਂ।',needHelp:'ਤੁਹਾਨੂੰ ਕਿਸ ਮਦਦ ਦੀ ਲੋੜ ਹੈ?',where:'ਕਿੱਥੇ?',startKnow:'ਜਿੱਥੋਂ ਤੁਸੀਂ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹੋ',lookingFor:'ਤੁਸੀਂ ਕੀ ਲੱਭ ਰਹੇ ਹੋ?',commonNeed:'ਤੁਹਾਨੂੰ ਮੈਡੀਕਲ ਸ਼ਬਦ ਜਾਣਨ ਦੀ ਲੋੜ ਨਹੀਂ। ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਇੱਕ ਆਮ ਲੋੜ ਚੁਣੋ।',meetGuide:'ਤੁਹਾਡਾ ਕੇਅਰ ਗਾਈਡ',notSure:'ਪਤਾ ਨਹੀਂ ਕਿੱਥੋਂ ਸ਼ੁਰੂ ਕਰਨਾ ਹੈ?',askCuro:'ਕਿਊਰੋ ਨੂੰ ਪੁੱਛੋ।',morePeople:'ਹੋਰ ਲੋਕਾਂ ਲਈ ਸਿਹਤ ਸੇਵਾ',languageTitle:'ਕਿਊਰੋ ਆਪਣੀ ਪਸੰਦ ਦੀ ਭਾਸ਼ਾ ਵਿੱਚ ਵਰਤੋ।',languageText:'ਲੋੜੀਂਦੀ ਜਾਣਕਾਰੀ ਗੁਆਏ ਬਿਨਾਂ ਭਾਸ਼ਾ ਬਦਲੋ।',ready:'ਜਦੋਂ ਤੁਸੀਂ ਤਿਆਰ ਹੋ',ctaTitle:'ਥੋੜ੍ਹੀ ਹੋਰ ਸਪਸ਼ਟਤਾ ਨਾਲ ਇਲਾਜ ਲੱਭੋ।',startSearching:'ਖੋਜ ਸ਼ੁਰੂ ਕਰੋ',academic:'ਅਕਾਦਮਿਕ ਪ੍ਰੋਟੋਟਾਈਪ'},
  Bengali:{topLine:'স্বাস্থ্য তথ্য বোঝা আরও সহজ',accessibility:'অ্যাক্সেসিবিলিটি',findCare:'চিকিৎসা খুঁজুন',howItWorks:'কীভাবে কাজ করে',assistant:'হেলথ অ্যাসিস্ট্যান্ট',eyebrow:'স্পষ্ট তথ্য দিয়ে যত্নের শুরু',heroTitle:'সঠিক চিকিৎসা খুঁজুন,',heroEm:'অনুমান ছাড়াই।',heroText:'অবস্থা, স্থান, চিকিৎসা, সুবিধা এবং আনুমানিক খরচ অনুযায়ী হাসপাতাল খুঁজুন — এক জায়গায়।',needHelp:'আপনার কী ধরনের সাহায্য দরকার?',where:'কোথায়?',startKnow:'যা জানেন তা দিয়ে শুরু করুন',lookingFor:'আপনি কী খুঁজছেন?',commonNeed:'মেডিকেল শব্দ জানা জরুরি নয়। শুরু করতে একটি সাধারণ প্রয়োজন বেছে নিন।',meetGuide:'আপনার কেয়ার গাইড',notSure:'কোথা থেকে শুরু করবেন বুঝতে পারছেন না?',askCuro:'কিউরোকে জিজ্ঞেস করুন।',morePeople:'আরও মানুষের জন্য স্বাস্থ্যসেবা',languageTitle:'আপনার স্বাচ্ছন্দ্যের ভাষায় কিউরো ব্যবহার করুন।',languageText:'প্রয়োজনীয় তথ্য না হারিয়ে ভাষা বদলান।',ready:'আপনি যখন প্রস্তুত',ctaTitle:'আরও একটু স্পষ্টতার সঙ্গে চিকিৎসা খুঁজুন।',startSearching:'খোঁজা শুরু করুন',academic:'একাডেমিক প্রোটোটাইপ'},
  Tamil:{topLine:'சுகாதார தகவலை எளிதாக புரிந்துகொள்ளுங்கள்',accessibility:'அணுகல்தன்மை',findCare:'சிகிச்சையைத் தேடுங்கள்',howItWorks:'எப்படி செயல்படுகிறது',assistant:'ஹெல்த் உதவியாளர்',eyebrow:'தெளிவுடன் சிகிச்சையைத் தொடங்குங்கள்',heroTitle:'சரியான சிகிச்சையைத் தேடுங்கள்,',heroEm:'ஊகமின்றி.',heroText:'நிலை, இடம், சிகிச்சை, வசதிகள் மற்றும் மதிப்பிடப்பட்ட செலவு அடிப்படையில் மருத்துவமனைகளை ஒரே இடத்தில் தேடுங்கள்.',needHelp:'எந்த உதவி தேவை?',where:'எங்கே?',startKnow:'உங்களுக்குத் தெரிந்தவற்றில் தொடங்குங்கள்',lookingFor:'நீங்கள் எதைத் தேடுகிறீர்கள்?',commonNeed:'மருத்துவச் சொல் தெரிந்திருக்க வேண்டியதில்லை. தொடங்க ஒரு பொதுவான தேவையைத் தேர்வு செய்யுங்கள்.',meetGuide:'உங்கள் கேர் வழிகாட்டி',notSure:'எங்கிருந்து தொடங்குவது தெரியவில்லையா?',askCuro:'க்யூரோவிடம் கேளுங்கள்.',morePeople:'மேலும் பலருக்கான சுகாதாரம்',languageTitle:'உங்களுக்கு வசதியான மொழியில் க்யூரோவைப் பயன்படுத்துங்கள்.',languageText:'தேவையான தகவலை இழக்காமல் மொழியை மாற்றுங்கள்.',ready:'நீங்கள் தயாராக இருக்கும்போது',ctaTitle:'சற்று அதிக தெளிவுடன் சிகிச்சையைத் தேடுங்கள்.',startSearching:'தேடலைத் தொடங்குங்கள்',academic:'கல்வி முன்மாதிரி'}
 };
 function apply(lang){const t=T[lang]||T.English;document.querySelectorAll('[data-i18n]').forEach(el=>{if(t[el.dataset.i18n])el.textContent=t[el.dataset.i18n]});document.querySelectorAll('.language-btn').forEach(b=>b.innerHTML=`<span aria-hidden="true">◎</span> ${lang} <span class="chevron">⌄</span>`);localStorage.setItem('curoLang',lang)}
 const lang=localStorage.getItem('curoLang')||'English';apply(lang);
 document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>apply(btn.dataset.lang)));
})();
